modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    #logoFile="examplemod.png" #optional
    authors="${mod_authors}" #optional
    description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ae2"
    mandatory=true
    versionRange="[${ae2_version},)"
    ordering="AFTER"
    side="BOTH"
